//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// ImagePocke_res.rc

#define IDC_STATIC                          -1

#define IDB_TOOLBAR                         100

#define IDI_MAIN                            100

#define IDR_MAINMENU                        100
#define IDR_MAINACCEL                       101

#define IDS_APPNAME                         100
#define IDS_VERSIONINFO                     101
#define IDS_QUERYSAVE                       102
#define IDS_UNTITLED                        103
#define IDS_SAVEAS                          104
#define IDS_IPKFILTER                       105
#define IDS_TITLEWITHNAME                   106
#define IDS_TITLEWITHNAMEMODIFIED           107
#define IDS_OPEN                            108
#define IDS_READY                           109
#define IDS_EXECUTINGCMD                    110

#define ID_NEW                              100
#define ID_OPEN                             101
#define ID_SAVE                             102
#define ID_SAVE_AS                          103
#define ID_PAGE_LAYOUT                      104
#define ID_PRINT_PREVIEW                    105
#define ID_PRINT                            106
#define ID_EXPORT_PDF                       107
#define ID_EXPORT_SQL                       108
#define ID_EXIT                             109
#define ID_UNDO                             110
#define ID_REDO                             111
#define ID_CUT                              112
#define ID_COPY                             113
#define ID_PASTE                            114
#define ID_SELECT_ALL                       115
#define ID_FIND                             116
#define ID_REPLACE                          117
#define ID_CLEAR                            118
#define ID_STATUS_BAR                       119
#define ID_TOOL_BAR                         120
#define ID_VIEW_STANDARD                    121
#define ID_VIEW_LIST                        122
#define ID_ZOOM_50                          123
#define ID_ZOOM_75                          124
#define ID_ZOOM_100                         125
#define ID_ZOOM_150                         126
#define ID_ZOOM_200                         127
#define ID_ZOOM                             128
#define ID_VIEW_IMAGES                      129
#define ID_VIEW_BORDERS                     130
#define ID_TEXT_BOLD                        131
#define ID_TEXT_ITALIC                      132
#define ID_TEXT_UNDERLINE                   133
#define ID_TEXT_UPPERCASE                   134
#define ID_TEXT_LOWERCASE                   135
#define ID_TEXT_TITLECASE                   136
#define ID_TEXT_FULLWIDTH                   137
#define ID_TEXT_HALFWIDTH                   138
#define ID_TEXT_HIRAGANA                    139
#define ID_TEXT_KATAKANA                    140
#define ID_TEXT_COLOR                       141
#define ID_TEXT_FONT                        142
#define ID_IMAGE_SIZE                       143
#define ID_IMAGE_SIZE_AUTO                  144
#define ID_IMAGE_SIZE_FIXED                 145
#define ID_IMAGE_TRIMMING                   146
#define ID_IMAGE_KEEP_ASPECT                147
#define ID_IMAGE_ROTATE_90                  148
#define ID_IMAGE_ROTATE_180                 149
#define ID_IMAGE_ROTATE_270                 150
#define ID_IMAGE_FLIP_V                     151
#define ID_IMAGE_FLIP_H                     152
#define ID_IMAGE_NO_ROTATE                  153
#define ID_IMAGE_BRIGHTNESS                 154
#define ID_IMAGE_HUE                        155
#define ID_IMAGE_AUTO_COLOR                 156
#define ID_IMAGE_FILTER_BLUR                157
#define ID_IMAGE_FILTER_SHARPEN             158
#define ID_LINE_SPACE_1                     159
#define ID_LINE_SPACE_1_5                   160
#define ID_LINE_SPACE_2                     161
#define ID_INDENT_INCREASE                  162
#define ID_INDENT_DECREASE                  163
#define ID_ALIGN_LEFT                       164
#define ID_ALIGN_CENTER                     165
#define ID_ALIGN_RIGHT                      166
#define ID_VALIGN_TOP                       167
#define ID_VALIGN_MIDDLE                    168
#define ID_VALIGN_BOTTOM                    169
#define ID_CELLS                            170
#define ID_ROW_HEIGHT                       171
#define ID_ROW_HIDE                         172
#define ID_ROW_SHOW                         173
#define ID_COLUMN_WIDTH                     174
#define ID_COLUMN_HIDE                      175
#define ID_COLUMN_SHOW                      176
#define ID_CELL_MERGE                       177
#define ID_CELL_SPLIT                       178
#define ID_SHOW_README                      179
#define ID_ABOUT                            180
#define ID_VIEW_TEXTS                       181
#define ID_ZOOM_IN                          182
#define ID_ZOOM_OUT                         183

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    102
        #define _APS_NEXT_COMMAND_VALUE     184
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
